spring.application.name=warehouse-management-system
spring.datasource.url=jdbc:postgresql://localhost:5432/wms_db
spring.datasource.username=${wms_DB_USERNAME}
spring.datasource.password=${wms_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080